export enum FormRuleType {
    string = 'string',
    number = 'number',
    boolean = 'boolean',
    method = 'method',
    regexp = 'regexp',
    integer = 'integer',
    float = 'float',
    array = 'array',
    object = 'object',
    enum = 'enum',
    date = 'date',
    url = 'url',
    hex = 'hex',
    email = 'email',
}
